apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: iframely
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: iframely
    namespace: flux-system
  values:
    image:
      registry: "docker.io"
      repository: qyg2297248353/iframely
      tag: latest
    configMap:
      name: iframely-config
