apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: outline
spec:
  interval: 5m
  chart:
    spec:
      chart: outline
      version: 0.3.4
      sourceRef:
        kind: HelmRepository
        name: community-charts
        namespace: flux-system
  values:
    image:
      tag: "0.84.0"
    url: "https://outline.sshme.in"
    externalPostgresql:
      host: "10.10.10.3"
      username: "outline_editor"
      existingSecret: "postgres-outline-password"
    externalRedis:
      host: "redis-master.storage.svc.cluster.local"
      port: 6379
      existingSecret: "redis-secret"
    fileStorage:
      mode: "s3"
      
      s3:
        existingSecret: "minio-outline"
        bucket: "outline"
        bucketUrl: "https://storage.sshme.in:9000"

    extraEnvVars:
      OIDC_CLIENT_ID: "outline"
      OIDC_AUTH_URI: "https://keycloak.sshme.in/realms/sshme-in/protocol/openid-connect/auth"
      OIDC_TOKEN_URI: "https://keycloak.sshme.in/realms/sshme-in/protocol/openid-connect/token"
      OIDC_USERINFO_URI: "https://keycloak.sshme.in/realms/sshme-in/protocol/openid-connect/userinfo"
      OIDC_LOGOUT_URI: "https://keycloak.sshme.in/realms/sshme-in/protocol/openid-connect/logout"
      OIDC_USERNAME_CLAIM: "preferred_username"
      OIDC_DISPLAY_NAME: "Keycloak"
      OIDC_SCOPES: "openid profile email"

  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: outline
            patch: |-
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: OIDC_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: keycloak-outline
                      key: OIDC_CLIENT_SECRET
