apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: outline
spec:
  interval: 5m
  chart:
    spec:
      chart: outline
      version: 0.3.4
      sourceRef:
        kind: HelmRepository
        name: community-charts
        namespace: flux-system
  values:
    url: "https://outline.sshme.in"
    postgresql:
      enabled: true
      auth:
        username: "outline"
        password: "outline"
        database: outline
    redis:
      enabled: true
    extraEnvVars:
      OIDC_CLIENT_ID: "outline"
      OIDC_AUTH_URI: "https://keycloak.sshme.in/realms/sshme-in/protocol/openid-connect/auth"
      OIDC_TOKEN_URI: "https://keycloak.sshme.in/realms/sshme-in/protocol/openid-connect/token"
      OIDC_USERINFO_URI: "https://keycloak.sshme.in/realms/sshme-in/protocol/openid-connect/userinfo"
      OIDC_LOGOUT_URI: "https://keycloak.sshme.in/realms/sshme-in/protocol/openid-connect/logout"
      OIDC_USERNAME_CLAIM: "preferred_username"
      OIDC_DISPLAY_NAME: "Keycloak"
      OIDC_SCOPES: "openid profile email"

  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: outline
            patch: |-
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: OIDC_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: sshme-in-keycloak-outline
                      key: OIDC_CLIENT_SECRET
