apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: outline-route
spec:
  parentRefs:
  - name: default-gateway
    namespace: istio-ingress
  hostnames:
  - "outline.sshme.in"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: outline
      port: 3000