apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: influxv2
spec:
  interval: 10m
  chart:
    spec:
      chart: influxdb2
      sourceRef:
        kind: HelmRepository
        name: influxdata
        namespace: flux-system
  values:
    adminUser:
      existingSecret: influxdb2-auth
    persistence:
      enabled: false

    