apiVersion: v1
kind: Secret
metadata:
    name: influxdb2-auth
type: Opaque
stringData:
    admin-token: ENC[AES256_GCM,data:E0zDs1ERmDrXnRcg6YCi337z+0hpqguf5g==,iv:4oUGz+ojbpa5Q/EJ3lxb0841YK6YR44NzpVxDozRE+E=,tag:XQNOMDmnJB7PD+8Y/1/L5A==,type:str]
    admin-password: ENC[AES256_GCM,data:/42vF0XySHC99n6pOVUAMYsjLXQ2XipR3Q==,iv:uMJgIgX3VUo9+yx0FC3AEVVHoVUTBUZYzm+IwQgV8l4=,tag:BRw0kXSttaYD50DSGvLMMg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qjz5x6ffkx0gg9pvwqxulg5tnlgww7vrld6m75j7mxclgseacgjqk0tzcx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXdnJEVVg1dE5VMUFFalcz
            S1kydzZYRVdzRk0ySUVFRjlNSXpUZi93bVc4CnZYQUJxdDBBazhwd3JuUy92aFB1
            VGczbngzVjRDN08rcU55NC9qYmFvdjgKLS0tIE42RXJWN214Wk53UTVFQWhTd1ov
            bEJqeTFSTjlVelZKVTVlN0J6bVhHSlEKrza6XiHj0cuHuiIc/ZJ6SfsLkFYvm3jK
            KrCAZWGwx4fwpMEUxiozviRMcIZZplhzjz0VjTLpzGCyJENVIhHY7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-14T07:40:52Z"
    mac: ENC[AES256_GCM,data:7xokoxnvtU9M+0OaELrMqsHiY9m7sxnINOcxvs+AoZ20Z/oDr6wVoA9BTfTrkruXuNLjDuX2WRWJyA9jhTHGpY2CTEu/RQcHbdzc2V5HMzcNxnxP2UdqMQ2KtSZylMm7qtjocYcHehbk1TD7VSbxnH9iHVe00NLCyJ0SzmuGf+A=,iv:vIouYtjCvTjJZWnVbgQHrFHG1jhg9OtQIOSIwOA7B8E=,tag:Vkmn7zUO+0JVSI6lovauPQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
