apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
spec:
  interval: 5m
  chart:
    spec:
      chart: grocy
      version: 8.5.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system