apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
spec:
  interval: 5m
  chart:
    spec:
      chart: homepage
      sourceRef:
        kind: HelmRepository
        name: homepage
        namespace: flux-system
  values:
    extraEnv:
      - name: HOMEPAGE_ALLOWED_HOSTS
        value: home2.sshme.in
    podAnnotations:
      reloader.stakater.com/auto: "true"
    serviceAccount:
      create: true
      name: homepage 
    volumes:
          - name: homepage-configs
            configMap:
              name: homepage-configs
    volumeMounts:
      - name: homepage-configs
        mountPath: /app/config/settings.yaml
        subPath: settings.yaml
        readOnly: true
      - name: homepage-configs
        mountPath: /app/config/bookmarks.yaml
        subPath: bookmarks.yaml
        readOnly: true
      - name: homepage-configs
        mountPath: /app/config/services.yaml
        subPath: services.yaml
        readOnly: true
      - name: homepage-configs
        mountPath: /app/config/widgets.yaml
        subPath: widgets.yaml
        readOnly: true
      - name: homepage-configs
        mountPath: /app/config/kubernetes.yaml
        subPath: kubernetes.yaml
        readOnly: true
      - name: homepage-configs
        mountPath: /app/config/docker.yaml
        subPath: docker.yaml
        readOnly: true
      - name: homepage-configs
        mountPath: /app/config/custom.css
        subPath: custom.css
        readOnly: true
      - name: homepage-configs
        mountPath: /app/config/custom.js
        subPath: custom.js
        readOnly: true