apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: homepage-route
spec:
  parentRefs:
    - name: default-gateway
      namespace: istio-ingress
  hostnames:
    - home.sshme.in
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: homepage
          port: 80