apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: homepage2-route
spec:
  parentRefs:
    - name: default-gateway
      namespace: istio-ingress
  hostnames:
    - home2.sshme.in
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: homepage2
          port: 10352