apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coder
spec:
  interval: 10m
  chart:
    spec:
      chart: coder
      sourceRef:
        kind: HelmRepository
        name: coder
        namespace: flux-system
  values:
    service:
      type: ClusterIP


