apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coder
spec:
  interval: 5m
  chart:
    spec:
      chart: coder
      version: 2.21.0
      sourceRef:
        kind: HelmRepository
        name: coder-v2
        namespace: flux-system
  values:
    coder:
      env:
        - name: CODER_ACCESS_URL
          value: "https://code.sshme.in"
        - name: CODER_VERBOSE
          value: "false"
        - name: CODER_DISABLE_PASSWORD_AUTH
          value: "true"
        - name: CODER_PG_CONNECTION_URL
          valueFrom:
            secretKeyRef:
              name: coder-db-url
              key: url
        - name: CODER_OAUTH2_GITHUB_DEFAULT_PROVIDER_ENABLE
          value: "false"
        - name: CODER_OIDC_ISSUER_URL
          value: "https://keycloak.sshme.in/realms/sshme-in"
        - name: CODER_OIDC_CLIENT_ID
          value: "code-server"
        - name: CODER_OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: coder-oidc-secret
              key: CODER_OIDC_CLIENT_SECRET
      service:
        type: ClusterIP
        
      #containers:
      #  - name: coder
      #    volumeMounts:
      #      - name: docker-socket
      #        mountPath: /var/run/docker.sock
      #    env:
      #      - name: DOCKER_HOST
      #        value: "tcp://localhost:2375"  
      #  - name: docker
      #    image: docker:19.03.12-dind
      #    privileged: true 
      #    ports:
      #      - containerPort: 2375 
      #    env:
      #      - name: DOCKER_HOST
      #        value: "tcp://localhost:2375"
      #volumes:
      #  - name: docker-socket
      #    hostPath:
      #      path: /var/run/docker.sock
      #      type: Socket
