apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coder-db
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 16.6.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      username: coder
      database: coder-db
      existingSecret: coder-db-secret
      secretKeys:
        adminPasswordKey: admin-password
        userPasswordKey: user-password
    networkPolicy:
      enabled: false