apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: coder-route
spec:
  parentRefs:
  - name: default-gateway
    namespace: istio-ingress
  hostnames:
  - "code.sshme.in"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: coder
      port: 80