apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: theia
spec:
  interval: 5m
  chart:
    spec:
      chart: theia-cloud
      sourceRef:
        kind: HelmRepository
        name: eclipse-che/eclipse-che
        namespace: flux-system

