apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: influx
spec:
  interval: 10m
  chart:
    spec:
      chart: influxdb
      sourceRef:
        kind: HelmRepository
        name: influxdata
        namespace: flux-system