apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: theia-base
spec:
  interval: 5m
  chart:
    spec:
      chart: theia-cloud-base
      sourceRef:
        kind: HelmRepository
        name: theia-cloud-repo
        namespace: flux-system
 