apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kiali-server
  namespace: istio-system
spec:
  interval: 10m
  chart:
    spec:
      chart: kiali-server
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: flux-system
  values:
    auth:
      strategy: "anonymous"
    external_services:
      prometheus:
        url: "http://prometheus-server.monitoring.svc.cluster.local:80"
      grafana:
        enabled: true
        url: "http://grafana.monitoring:80"
        in_cluster_url: "http://grafana.monitoring:80"

    deployment:
      accessible_namespaces: ["**"]
