apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kiali-server
  namespace: istio-system
spec:
  interval: 10m
  chart:
    spec:
      chart: kiali-server
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: flux-system
  values:
    auth:
      strategy: "anonymous"
    external_services:
      prometheus:
        url:  "http://prometheus-kube-prometheus-prometheus.monitoring:9090"
      grafana:
        enabled: true
        url: "http://grafana.monitoring"
        in_cluster_url: "http://grafana.monitoring"
        auth:
          type: basic
          username: secret:grafana-auth:username
          password: secret:grafana-auth:password

    deployment:
      accessible_namespaces: ["**"]
      pod_labels:
        istio.io/dataplane-mode: "ambient"
