apiVersion: v1
kind: Secret
metadata:
    name: sops-age
stringData:
    age.agekey: ENC[AES256_GCM,data:KuolMN6N1yiVIASc+eAUktRkCD4sBGBG2Ysc8R3YYuftJIyQ5csQuf655hXVSJoy8hAju0g2LpWzWzkDmV0XBiD62n4Oo+ATfgsQW870tMkZGP5ucT7Vn0LeVUhYHEmfdM+C3yG41mlJx4oFk8kvNQyOyvGDht5Q0MMc2B8VMHVDBCqTcc7c2HmQSyrjiWaGt7fZ7Fh28kWwEnAKCsm9ZJg0MxfYN2Vz9zXitpOgk3xaJKUYsUxdXZAyUAo=,iv:fYOAwMO6nbt+0Z7EHxNDZgyMU1doipoGzVKJQN1ZAB8=,tag:wKRQH8BWeQCe+RRbzziQlw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qjz5x6ffkx0gg9pvwqxulg5tnlgww7vrld6m75j7mxclgseacgjqk0tzcx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4WkpnVnV1NXJOVmloYjk4
            Qlh6TWVVeHUvUjh3SEJoaTAwOGtzSEJjV3k4CjdBd1AvUEN3aTgvemZ6bHRjQmEr
            R2orQmtWU0VmU29hM3JqcVJOLzlmem8KLS0tIExhNlZFSnhKNVhrakVKSjA4VUhC
            dE5vcUR0amxFNkQwWkx3NjZFMTlRUGMKYzu5EU8eE1AK0pZ08bB1Mn7Jgiqj0QOT
            Z+3qoO8O1GeIdlpLJtGiURYhuNo/riY/OqDVUrm/W5rktkyl7Oosyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-03T16:37:13Z"
    mac: ENC[AES256_GCM,data:DP1ew9zqeztPICNIyRWzo0Ct4c6du5DW53GZEg4WUmVLLNnU+kryKpPtmKLpooM3DdEGGnrRXBZWmQoeZASGVkQdlwX4COP4KxkfgVN14CkDlJo4qVwYoT/N70JGGHZIb5benYzrT1tq+4ti+kfD64wvDZ40H5TuGmjXMb9UVb0=,iv:kXLuVAX5e6+LIfVPJNIntL5EBPYuEY3YFWS6w8BPru8=,tag:m7hAPhhsI7KeAL6/RtEY8A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
