apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
spec:
  interval: 5m
  chart:
    spec:
      chart: keycloak
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    networkPolicy:
      enabled: false
    postgresql:
      enabled: false
    externalDatabase:
      existingSecret: "postgres-config-keycloak"
      existingSecretHostKey: "host"
      existingSecretPortKey: "port"
      existingSecretUserKey: "user"
      existingSecretDatabaseKey: "database"
      existingSecretPasswordKey: "password"
    extraEnvVars:
      # - name: KC_HTTP_ENABLED
      #   value: "true"
      # - name: KC_BIND
      #   value: "0.0.0.0"
      # - name: KC_PROXY_HEADERS
      #   value: "xforwarded"
      ########################
      - name: KC_HTTP_ENABLED
        value: "true"
      - name: KC_PROXY
        value: "edge"
      - name: KC_PROXY_HEADERS
        value: xforwarded
      - name: KC_BIND
        value: "0.0.0.0"
      - name: KC_HOSTNAME
        value: https://keycloak.sshme.in
      - name: KC_HOSTNAME_ADMIN
        value: https://keycloak.sshme.in

    metrics:
      enabled: true
    serviceMonitor:
      enabled: true
      interval: 30s
