apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
spec:
  interval: 5m
  chart:
    spec:
      chart: keycloak
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    postgresql:
      enabled: false
    externalDatabase:
      existingSecret: "postgres-config-keycloak"
      existingSecretHostKey: "host"
      existingSecretPortKey: "port"
      existingSecretUserKey: "user"
      existingSecretDatabaseKey: "database"
      existingSecretPasswordKey: "password"
    extraEnvVars:
      - name: KC_HTTP_ENABLED
        value: "false"
      - name: KC_PROXY_HEADERS
        value: "xforwarded"
