apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
spec:
  interval: 5m
  chart:
    spec:
      chart: headlamp
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
  values:
    extraManifests:
      - |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: headlamp
          namespace: apps
        spec:
          template:
            spec:
              containers:
                - name: headlamp
                  env:
                    - name: NODE_ENV
                      value: development
     config:
      oidc:
        secret:
          create: false
        externalSecret:
          enabled: true
          name: "headlamp-oicd-secret"
  
     

