apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
spec:
  interval: 5m
  chart:
    spec:
      chart: headlamp
      version: 0.33.0
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
  values:
    pluginsManager:
      enabled: true
      configContent: |
        plugins:
          - name: flux
            source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_flux
            version: 0.4.0
        installOptions:
          parallel: true
          maxConcurrent: 2
      baseImage: node:lts-alpine
      version: latest
     config:
       oidc:
        secret:
          create: false
        externalSecret:
          enabled: true
          name: "headlamp-oicd-secret"
  
     

