apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
spec:
  interval: 5m
  chart:
    spec:
      chart: headlamp
      version: 0.33.0
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
  values:
    config:
       pluginsDir: /build/plugins
       oidc:
        secret:
          create: false
        externalSecret:
          enabled: true
          name: "headlamp-oicd-secret"
    initContainers:
      - command:
          - /bin/sh
          - -c
          - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/
        image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:latest
        imagePullPolicy: Always
        name: headlamp-plugins
        volumeMounts:
          - mountPath: /build/plugins
            name: headlamp-plugins
    persistentVolumeClaim:
      accessModes:
        - ReadWriteOnce
      enabled: true
      size: 1Gi
    volumeMounts:
      - mountPath: /build/plugins
        name: headlamp-plugins
    volumes:
      - name: headlamp-plugins
        persistentVolumeClaim:
          claimName: headlamp
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Service
            patch: |
              - op: add
                path: /metadata/labels/homepage.group
                value: Cluster
              - op: add
                path: /metadata/labels/homepage.name
                value: Headlamp
              - op: add
                path: /metadata/labels/homepage.icon
                value: mdi-kubernetes
              - op: add
                path: /metadata/labels/homepage.href
                value: http://headlamp.default.svc.cluster.local
  
     

