apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
spec:
  interval: 5m
  chart:
    spec:
      chart: headlamp
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
  values:
     config:
       oidc:
        secret:
          create: false
        externalSecret:
          enabled: true
          name: "headlamp-oicd-secret"
  
     

