apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kresus
spec:
  interval: 5m
  chart:
    spec:
      chart: kresus
      version: 0.2.0
      sourceRef:
        kind: HelmRepository
        name: rm3l
        namespace: flux-system