apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: goldilocks
spec:
  interval: 10m
  chart:
    spec:
      chart: goldilocks
      version: 9.1.0
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
  values:
    vpa:
      enabled: true
      updater:
        enabled: true
    controller:
      deployment:
        labels:
          app: goldilocks
    dashboard:
      deployment:
        labels:
          app: goldilocks-dashboard