apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vpa
  namespace: autoscaler
spec:
  interval: 10m
  chart:
    spec:
      chart: vpa
      version: 4.8.0
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system