apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-sdk-certificate
  namespace: external-secrets
spec:
  secretName: bitwarden-tls-certs
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
  dnsNames:
    - "bitwarden.sshme.in"