
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-source
  namespace: flux-system
spec:
  interval: 5m
  path: ./sshme-in/source
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system