apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: allow-ingress
  namespace: istio-ingress
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  mtls:
    mode: PERMISSIVE
