{
 "title": "APC UPS Dashboard",
 "description": "Inspiration taken from https://grafana.com/grafana/dashboards/10835 - Thank you, anthonysomerset.  I've corrected some math errors,  and updated it to work with multiple  UPSs in the same database.",
 "tags": [
  "telegraf",
  "apcupsd"
 ],
 "time": { "from": "now-1M/M", "to": "now-1M/M" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "upsdatasource", "label": "UPS Datasource", "query": "influxdb" },
   {
    "name": "upsname",
    "label": "UPS Name",
    "query": "SHOW TAG VALUES FROM apcupsd WITH KEY=ups_name"
   },
   {
    "name": "maxwatt",
    "label": "UPS Max Output Power Capacity (Watt)",
    "query": "SHOW TAG VALUES FROM apcupsd WITH KEY=model WHERE ups_name =~ /^$upsname$/"
   },
   { "name": "kwhprice", "label": "kWh Price", "query": ".15" },
   { "name": "currency", "label": "Currency", "query": "$,€,£,C$,kr,₽,¥,R" }
  ]
 },
 "panels": [
  {
   "title": "UPS Load %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "Percent" }
   ],
   "targets": [
    {
     "alias": "UPS Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery Charge",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Percent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "select": [
      [
       { "params": [ "battery_charge_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "UPS Runtime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "select": [
      [
       { "params": [ "time_left_ns" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "Current UPS Load",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Watts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT sum(\"load_percent\") / 100 * 865 FROM \"APC\" WHERE \"load_percent\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100*$maxwatt" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "Estimated Yearly Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Costs",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT sum(\"load_percent\") / 100 * 865 FROM \"APC\" WHERE \"load_percent\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/100*$maxwatt/1000*24*365" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Volts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT sum(\"load_percent\") / 100 * 865 FROM \"APC\" WHERE \"load_percent\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "input_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "Output Voltage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Volts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT sum(\"load_percent\") / 100 * 865 FROM \"APC\" WHERE \"load_percent\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "output_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "Estimated Yearly Cost",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Costs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT sum(\"load_percent\") / 100 * 865 FROM \"APC\" WHERE \"load_percent\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         "/100*$maxwatt/1000*24*$kwhprice*365"
        ],
        "type": "math"
       }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Volts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT sum(\"load_percent\") / 100 * 865 FROM \"APC\" WHERE \"load_percent\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "battery_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "Input Frequency",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Hz",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT sum(\"load_percent\") / 100 * 865 FROM \"APC\" WHERE \"load_percent\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "input_frequency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "Internal Temp",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "C",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT sum(\"load_percent\") / 100 * 865 FROM \"APC\" WHERE \"load_percent\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "internal_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "Past Day's Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT mean(\"load_percent\") /100*$maxwatt/1000/12 FROM \"apcupsd\" WHERE (\"ups_name\" =~ /^$upsname$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/100*$maxwatt/1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "UPS Load %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent", "label": "Percent" }
   ],
   "targets": [
    {
     "alias": "UPS Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT mean(\"load_percent\") FROM \"apcupsd\" WHERE (\"ups_name\" =~ /^$upsname$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 11, "y": 6 },
   "yaxes": [
    { "format": "kwatth", "label": "Consumption" }
   ],
   "targets": [
    {
     "alias": "kWh",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT sum(\"value\") FROM \"power\" WHERE \"host\" = 'mainpower' AND $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/100*$maxwatt/1000*24" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "Past Day's Cost",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Costs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT sum(\"load_percent\") / 100 * 865 FROM \"APC\" WHERE \"load_percent\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/100*$maxwatt/1000*$kwhprice" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "Past Month's Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "kWh",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT sum(\"load_percent\") / 100 * 865 FROM \"APC\" WHERE \"load_percent\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/100*$maxwatt/1000*24" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "Past Month's Cost",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT sum(\"load_percent\") / 100 * 865 FROM \"APC\" WHERE \"load_percent\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         "/100*$maxwatt/1000*24*$kwhprice"
        ],
        "type": "math"
       }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "UPS Load %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent", "label": "Percent" }
   ],
   "targets": [
    {
     "alias": "UPS Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT mean(\"load_percent\") FROM \"apcupsd\" WHERE (\"ups_name\" =~ /^$upsname$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 11, "y": 11 },
   "yaxes": [
    { "format": "kwatth", "label": "Consumption" }
   ],
   "targets": [
    {
     "alias": "kWh",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT sum(\"value\") FROM \"power\" WHERE \"host\" = 'mainpower' AND $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/100*$maxwatt/1000*24" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "Past Year's Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "kWh",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT sum(\"load_percent\") / 100 * 865 FROM \"APC\" WHERE \"load_percent\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/100*$maxwatt/1000*24" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "Past Year's Cost",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "SELECT sum(\"load_percent\") / 100 * 865 FROM \"APC\" WHERE \"load_percent\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         "/100*$maxwatt/1000*24*$kwhprice"
        ],
        "type": "math"
       }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  }
 ]
}