apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: actual
spec:
  interval: 5m
  chart:
    spec:
      chart: actualbudget
      version: 1.8.1
      sourceRef:
        kind: HelmRepository
        name: community-charts
        namespace: flux-system
  values:
    login:
      method: "openid"
      openid:
        enforce: true
        providerName: "Keycloak"
        discoveryUrl: "https://keycloak.sshme.in/realms/sshme-in/.well-known/openid-configuration"
        tokenExpiration: 3600
        existingSecret:
          name: "actual-oidc-secret"
          clientIdKey: "clientId"
          clientSecretKey: "clientSecret"
    persistence:
      enabled: true
    strategy:
      type: Recreate
    files:
      server: /data/server-files
      user: /data/user-files
