apiVersion: v1
kind: Secret
metadata:
    name: actual-oidc-secret
stringData:
    clientId: ENC[AES256_GCM,data:BK1DqpQj,iv:GWPuZObjvMQWiSGDftJ5IbtIv0lbU4vndMpbi/qymuU=,tag:6QKbDDYx0jFWI3vruHYQRg==,type:str]
    clientSecret: ENC[AES256_GCM,data:M2kljeg6NHLAZSLuQJmyLhRobdRA+M6aHzMi0urslEQ=,iv:goC2s7vMh1ZEn3K4dREzhhTUT6UAJWeJRwuZQ4fPCU8=,tag:q8nVprK1jVvxcpavEWXhlA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qjz5x6ffkx0gg9pvwqxulg5tnlgww7vrld6m75j7mxclgseacgjqk0tzcx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrRTZ0MFpaSmJHVGplVTZk
            Vm00VXZmTHcxQXAvWFg0R290aGI2eWtFbVdrCmphVEY0cTgrZDdCbVFGZnlzWlpH
            UnRDVTZ4K2dyNlNVVXFhbCt6WjczYWMKLS0tIDZGS3dCQ3U5Y3I5ajM5MDFkZVh5
            MGlxQzZDSE5YWE1JY01KbHYrWXhPVkUKFV0kCvoocAYV4zMptbiIziQh7Gntqr9n
            TUCY61pijfGlbmoHHtOO8l3WWbCepwDnYZr2ec/olmXiVv68ZDFGUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-14T17:23:55Z"
    mac: ENC[AES256_GCM,data:alxsMCf97R82jglTsc77ezNK9z2cCHSKLWiQJJ7RFzCogJi+bVcnCDz/SRodACAFp44SRkmasqepJ3iBHNXHX7zP6SnSNNhbmSIPjZa+fhci/Sn1vNnmws4/3Y2BZtD55r5AqRBD5Yp6FiEx7cKS2S5zdWC8kDeZIngA+buWLIY=,iv:RkaRahlwtTgEEIHglrMb7Gn77JPxVsOXBMSMH/JhaoM=,tag:YeDBBXjDI4jmNH0lxIyUCQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
