apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eclipse-che
spec:
  interval: 5m
  chart:
    spec:
      chart: eclipse-che
      version: 7.102.0
      sourceRef:
        kind: HelmRepository
        name: eclipse-che
        namespace: flux-system