apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: outline2-route
spec:
  parentRefs:
  - name: default-gateway
    namespace: istio-ingress
  hostnames:
  - "outline.sshme.in"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: outline2
      port: 3000