apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
spec:
  interval: 5m
  chart:
    spec:
      chart: homepage
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/gethomepage/homepage
      tag: v1.4.4@sha256:cd8da3c81ede2a072510930defdcf44c7a0473f72a6d5216beea3b13b3093afe
      pullPolicy: IfNotPresent

    persistence:
      config:
        enabled: false

    forceConfigFromValues: true

    workload:
      main:
        podSpec:
          automountServiceAccountToken: true
          initContainers:
            init-config:
              enabled: false
          containers:
            main:
              env:
                HOMEPAGE_ALLOWED_HOSTS: "home.sshme.in"
                # keep logs off /app/config
                LOG_TARGETS: "stdout"

    # Your config lives in values → rendered to a ConfigMap → mounted at /app/config/*
    configmap:
      config:
        enabled: true
        data:
          custom.js: ""
          custom.css: ""
          kubernetes.yaml: |
            mode: cluster
            gateway: true
          settings.yaml: |
            ---
            title: SSHM3-1N
            background:
              image: https://images.unsplash.com/photo-1508144753681-9986d4df99b3?q=80&w=3540&auto=format&fit=crop
              saturate: 50
              brightness: 50
            # ensure nothing tries to write under /app/config
            logpath: /tmp
            providers:
              openweathermap: openweathermapapikey
              weatherapi: weatherapiapikey

          widgets.yaml: |
            ---
            - search:
                provider: custom
                url: https://www.ecosia.org/search?q=
                target: _blank
                suggestionUrl: https://ac.ecosia.org/autocomplete?type=list&q=
                showSearchSuggestions: true

          services.yaml: |
            ---
            # your services go here

          bookmarks.yaml: |
            ---
            - Developer:
                - Github:
                    - abbr: GH
                      href: https://github.com/
                - Flux-Repo:
                    - abbr: GH
                      href: https://github.com/flbrun/flux-cluster

    # (unchanged) RBAC rules for discovery/widgets
    rbac:
      main:
        rules:
          - apiGroups:
              - gateway.networking.k8s.io
            resources:
              - httproutes
            verbs: ["get","list"]
          - apiGroups: [""]
            resources: ["namespaces","pods","nodes"]
            verbs: ["get","list"]
          - apiGroups: ["extensions","networking.k8s.io"]
            resources: ["ingresses"]
            verbs: ["get","list"]
          - apiGroups: ["metrics.k8s.io"]
            resources: ["nodes","pods"]
            verbs: ["get","list"]
          - apiGroups: ["apiextensions.k8s.io"]
            resources: ["customresourcedefinitions/status"]
            verbs: ["get"]
