apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
spec:
  interval: 5m
  chart:
    spec:
      chart: homepage
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                HOMEPAGE_ALLOWED_HOSTS: "home.sshme.in"
    persistence:
      config:
        enabled: true
    configmap:
      config:
        enabled: true
        data:
          custom.js: ""
          custom.css: ""
          kubernetes.yaml: |
            mode: cluster
          settings.yaml: |
            ---
            background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
          widgets.yaml: |
            ---
          services.yaml: |
            ---
            - Infra:
                - My First Service:
                    href: http://localhost/
                    description: Homepage is awesome
            - Apps:
                - My Third Service:
                    href: http://localhost/
                    description: Homepage is 😎
          bookmarks.yaml: |
            ---
            - Developer:
              - Github:
                  - abbr: GH
                    href: https://github.com/

    forceConfigFromValues: false