apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
spec:
  interval: 5m
  chart:
    spec:
      chart: homepage
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    image:

    # No PVCs anywhere
    persistence:
      # Writable runtime dir (tmpfs-like). This is NOT persistent.
      config:
        enabled: true
        type: emptyDir
        mountPath: /app/config
        targetSelector:
          main:
            main: {}
            copy-config: {}
      # Mount your rendered ConfigMap read-only at /seed/*
      seed:
        enabled: true
        type: configmap
        objectName: config
        mountPath: /seed
        readOnly: true
        targetSelector:
          main:
            copy-config: {}

    # Do NOT let the chart mount files directly into /app/config (we copy ourselves)
    forceConfigFromValues: false

    workload:
      main:
        podSpec:
          automountServiceAccountToken: true
          initContainers:
            # Disable the chart's init (if it exists) and use our own simple copier
            init-config:
              enabled: false
            copy-config:
              image: busybox:1.36
              command:
                - sh
                - -ce
                - |
                  mkdir -p /app/config
                  cp -a /seed/. /app/config/
          containers:
            main:
              env:
                HOMEPAGE_ALLOWED_HOSTS: "home.sshme.in"
                # keep writes off /app/config
                LOG_TARGETS: "stdout"

    # Your config lives in values -> rendered into a single ConfigMap named "config"
    configmap:
      config:
        enabled: true
        data:
          custom.js: ""
          custom.css: ""
          kubernetes.yaml: |
            mode: cluster
            gateway: true
          settings.yaml: |
            ---
            title: SSHM3-1N
            background:
              image: https://images.unsplash.com/photo-1508144753681-9986d4df99b3?q=80&w=3540&auto=format&fit=crop
              saturate: 50
              brightness: 50
            # ensure runtime writes go somewhere writable
            logpath: /tmp
            providers:
              openweathermap: openweathermapapikey
              weatherapi: weatherapiapikey
          widgets.yaml: |
            ---
            - search:
                provider: custom
                url: https://www.ecosia.org/search?q=
                target: _blank
                suggestionUrl: https://ac.ecosia.org/autocomplete?type=list&q=
                showSearchSuggestions: true
          services.yaml: |
            ---
          bookmarks.yaml: |
            ---
            - Developer:
                - Github:
                    - abbr: GH
                      href: https://github.com/
                - Flux-Repo:
                    - abbr: GH
                      href: https://github.com/flbrun/flux-cluster

    rbac:
      main:
        rules:
          - apiGroups: ["gateway.networking.k8s.io"]
            resources: ["httproutes"]
            verbs: ["get","list"]
          - apiGroups: [""]
            resources: ["namespaces","pods","nodes"]
            verbs: ["get","list"]
          - apiGroups: ["extensions","networking.k8s.io"]
            resources: ["ingresses"]
            verbs: ["get","list"]
          - apiGroups: ["metrics.k8s.io"]
            resources: ["nodes","pods"]
            verbs: ["get","list"]
          - apiGroups: ["apiextensions.k8s.io"]
            resources: ["customresourcedefinitions/status"]
            verbs: ["get"]
