apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
spec:
  interval: 5m
  chart:
    spec:
      chart: homepage
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system