apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
spec:
  interval: 5m
  chart:
    spec:
      chart: homepage
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    workload:
      main:
        podSpec:
          # Copy seed config into the writable /app/config before the app starts
          initContainers:
            copy-config:
              image: busybox:1.36
              command:
                - sh
                - -ce
                - |
                  mkdir -p /app/config
                  cp -a /seed/. /app/config/
          containers:
            main:
              env:
                HOMEPAGE_ALLOWED_HOSTS: "home.sshme.in"
                LOG_TARGETS: "stdout"

    persistence:
      # Writable config dir – no PVC
      config:
        enabled: true
        type: emptyDir
        mountPath: /app/config
      # Read-only mount of the generated ConfigMap at /seed
      seed:
        enabled: true
        type: configmap
        objectName: config          # points at configmap.config below
        mountPath: /seed
        readOnly: true

    configmap:
      config:
        enabled: true
        data:
          custom.js: ""
          custom.css: ""
          kubernetes.yaml: |
            mode: cluster
            gateway: true
          settings.yaml: |
            ---
            title: SSHM3-1N
            background:
              image: https://images.unsplash.com/photo-1508144753681-9986d4df99b3?q=80&w=3540&auto=format&fit=crop
              saturate: 50
              brightness: 50
            logpath: /tmp
            providers:
              openweathermap: openweathermapapikey
              weatherapi: weatherapiapikey
          widgets.yaml: |
            ---
            - search:
                provider: custom
                url: https://www.ecosia.org/search?q=
                target: _blank
                suggestionUrl: https://ac.ecosia.org/autocomplete?type=list&q=
                showSearchSuggestions: true
          services.yaml: |
            ---
          bookmarks.yaml: |
            ---
            - Developer:
                - Github:
                    - abbr: GH
                      href: https://github.com/
                - Flux-Repo:
                    - abbr: GH
                      href: https://github.com/flbrun/flux-cluster

    forceConfigFromValues: false

    rbac:
      main:
        rules:
          - apiGroups: ["gateway.networking.k8s.io"]
            resources: ["httproutes"]
            verbs: ["get","list"]
          - apiGroups: [""]
            resources: ["namespaces","pods","nodes"]
            verbs: ["get","list"]
          - apiGroups: ["extensions","networking.k8s.io"]
            resources: ["ingresses"]
            verbs: ["get","list"]
          - apiGroups: ["metrics.k8s.io"]
            resources: ["nodes","pods"]
            verbs: ["get","list"]
          - apiGroups: ["apiextensions.k8s.io"]
            resources: ["customresourcedefinitions/status"]
            verbs: ["get"]
