---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homepage-min-read
rules:
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - httproutes
    verbs: ["get","list"]

  - apiGroups: [""]
    resources:
      - namespaces
      - pods
      - nodes
    verbs: ["get","list"]

  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
    verbs: ["get","list"]

  - apiGroups:
      - metrics.k8s.io
    resources:
      - nodes
      - pods
    verbs: ["get","list"]

  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
      - customresourcedefinitions/status
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homepage-min-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: homepage-min-read
subjects:
  - kind: ServiceAccount
    name: homepage
    namespace: apps
