apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hedgedoc
spec:
  interval: 5m
  chart:
    spec:
      chart: hedgedoc
      version: 0.5.4
      sourceRef:
        kind: HelmRepository
        name: adfinis
        namespace: flux-system
  values:
    postgresql:
      enabled: false
    externalDatabase:
      username: "hedgedoc"
      password: "passwort"
      host: "10.10.10.3"