apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-upgrade-controller
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: system-upgrade
  path: ./manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: system-upgrade-controller
  targetNamespace: system-upgrade
  wait: true